export const ACTIVITIES_REQUEST = "ACTIVITIES_REQUEST";
export const ACTIVITIES_SUCCESS = "ACTIVITIES_SUCCESS";
export const ACTIVITIES_FAILURE = "ACTIVITIES_FAILURE";
export const CLEAR_ALL = "CLEAR_ALL";