export const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";

export const GET_TEAM_JOBS_REQUEST = "GET_TEAM_JOBS_REQUEST";
export const GET_TEAM_JOBS_SUCCESS = "GET_TEAM_JOBS_SUCCESS";
export const GET_TEAM_JOBS_FAILURE = "GET_TEAM_JOBS_FAILURE";

export const GET_JOB_DETAILS_REQUEST = "GET_JOB_DETAILS_REQUEST";
export const GET_JOB_DETAILS_SUCCESS = "GET_JOB_DETAILS_SUCCESS";
export const GET_JOB_DETAILS_FAILURE = "GET_JOB_DETAILS_FAILURE";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAILURE = "DELETE_JOB_FAILURE";

export const EDIT_JOB_DETAILS_REQUEST = "EDIT_JOB_DETAILS_REQUEST";
export const EDIT_JOB_DETAILS_SUCCESS = "EDIT_JOB_DETAILS_SUCCESS";
export const EDIT_JOB_DETAILS_FAILURE = "EDIT_JOB_DETAILS_FAILURE";

export const CLEAR_ALL = "CLEAR_ALL";

export const CLEAR_STATUS = "CLEAR_STATUS";

export const APPLY_JOB = "APPLY_JOB";
export const NO_APPLY_JOB = "NO_APPLY_JOB";

export const SAVE_APPLY_JOB_REQUEST = "SAVE_APPLY_JOB_REQUEST";
export const SAVE_APPLY_JOB_SUCCESS = "SAVE_APPLY_JOB_SUCCESS";
export const SAVE_APPLY_JOB_FAILURE = "SAVE_APPLY_JOB_FAILURE";

export const SEARCH_JOBS = "SEARCH_JOBS"

export const SELECTED_DELETE_JOB ="SELECTED_DELETE_JOB"