// create JOB

export const CHANGE_CREATE_JOB_FORM = "CHANGE_CREATE_JOB_FORM";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAILURE = "CREATE_JOB_FAILURE";


export const GET_JOB_DETAILS_REQUEST = "GET_JOB_DETAILS_REQUEST";
export const GET_JOB_DETAILS_SUCCESS = "GET_JOB_DETAILS_SUCCESS";
export const GET_JOB_DETAILS_FAILURE = "GET_JOB_DETAILS_FAILURE";

export const EDIT_JOB_DETAILS_REQUEST = "EDIT_JOB_DETAILS_REQUEST";
export const EDIT_JOB_DETAILS_SUCCESS = "EDIT_JOB_DETAILS_SUCCESS";
export const EDIT_JOB_DETAILS_FAILURE = "EDIT_JOB_DETAILS_FAILURE";

export const CLEAR_CREATE_JOB_RESPONSE = "CLEAR_CREATE_JOB_RESPONSE";

export const CLEAR_ALL = "CLEAR_ALL";

export const CLEAR_STATUS = "CLEAR_STATUS";